### ISSUE TITLE
--gap option not present

### ISSUE THREAD

**Issue by sp-eldata** [maximilianh/crisporWebsite#3]
The documentation says that --gap is to allow gaps in the match. When I try to run with that parameter, I get: 
`crispor.py: error: no such option: --gap`

Is that option to be incorporated in the future?

**Comment by maximilianh** [comment]
I've removed this option because gaps are not an issue. You can see from my paper that in the whole literature and all off-target assays, only two were ever observed and their cleavage rates were very low. Searching for gaps leads to a large increase of predicted off-targets that is not practical to test anymore. Also, it increased the complexity of the code and was very hard to display on the website. You can probably put the code back in by going back through git history, but I have no reason at the moment to put gaps back in.

Thanks for pointing out the documentation error, I've fixed it and added the --bowtie option instead to the README.
