### ISSUE TITLE
potential bug, hitBestMismCount not updated with the minimal value

### ISSUE THREAD

**Issue by mbsimonovic** [maximilianh/crisporWebsite#8]
looking at the https://github.com/maximilianh/crisporWebsite/blob/5397d8770e2a41514f28c77d12bd1a16455a42e7/crispor.py#L3029
```
           oldMismCount = hitBestMismCount.get(hitId, 9999)
           if mismCount < oldMismCount:
               hit = (mismCount, guideIdWithMod, strand, chrom, start, tSeq, modifParts)
               posToHit[hitId] = hit
```
wasn't `hitBestMismCount` supposed to be updated with the newly found minimum:

```
           oldMismCount = hitBestMismCount.get(hitId, 9999)
           if mismCount < oldMismCount:
               hit = (mismCount, guideIdWithMod, strand, chrom, start, tSeq, modifParts)
               posToHit[hitId] = hit
               hitBestMismCount[hitId] = mismCount # bugfix
```

 like it stands now, whichever count happens to be the last wins.

**Comment by maximilianh** [comment]
Ooops, sorry, I forgot about this issue! 

It's actually not important, as bowtie should not be used as the aligner, since it misses to many alignments. How did you stumble over this? Did you use bowtie?

Either way, thanks, I've added your change now and acknowledge you in a comment.

NB: I've written a protein interaction viewer a few years ago and would love to chat about your thoughts on protein interaction viewers. I saw that you're working on String and Cytoscape...

**Comment by mbsimonovic** [comment]
@maximilianh i've been looking for a short read aligner and was reading the code to see how you managed to get up to 4bp mismatches since bowtie only gives up to 3. Btw bwa misses even more hits :) here's my email to [the bwa mailing list](https://sourceforge.net/p/bio-bwa/mailman/message/36190558/), and 6months later still no reply.. I'd be happy to chat, you have my email ( firstname dot lastname at imls.uzh.ch)?

**Comment by maximilianh** [comment]
I'm curious to hear about this. My email is max@soe.ucsc.edu. Did you see
how I'm calling BWA? This should find all matches...
